apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-v5o3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-v5o3@sha256:b8cf070ad4e7acf3b49b4ca85d9fbd9a03db01f9bb6291e5eac2c11197f5f091
        name: my-nodejs
        resources: {}
status: {}
